name: Objekt Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 */5 * * *'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make envfile
      run: |
        cat <<'EOF' > .env
        BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        EOF

    - name: run Python script
      run: python main.py
